## Analyzer extension: generated asset registries.
##
## Scripts containing any of the config "registry_markers" strings (or
## listed in "registry_scripts") map member names to asset paths. Their
## asset paths are not marked wholesale — only members referenced from used
## code (member access `Class.Member`, or the member name as a quoted
## string to stay fail-open for dynamic key access) pull their assets in.
##
## Four generator shapes are recognized:
##   "Key": "res://path"                      (const _paths dictionary)
##   static var Key = "res://path"            (string-path members)
##   static var Key: T = preload("res://p")   (direct preload members)
##   static var Key: W = Wrapper.new("Key")   (indirect members; paths come
##                                             from config registry_patterns,
##                                             string or array of templates
##                                             with a {member} placeholder)
extends RefCounted

var _markers: Array = []
var _scripts: Array = []
var _patterns := {}
## class_name -> { script: String,
##                 members: {member: Array[String] asset paths},
##                 used: {member: String evidence} }
var _registries := {}

var _re_class := RegEx.create_from_string("(?m)^class_name\\s+([A-Za-z_]\\w*)")
var _re_dictpath := RegEx.create_from_string("\"([A-Za-z_]\\w*)\"\\s*:\\s*\"(res://[^\"]+)\"")
var _re_strpath := RegEx.create_from_string("(?m)^static\\s+var\\s+([A-Za-z_]\\w*)[^=\\n]*:?=\\s*\"(res://[^\"]+)\"")
var _re_preload := RegEx.create_from_string("(?m)^static\\s+var\\s+([A-Za-z_]\\w*)[^=\\n]*=\\s*preload\\(\\s*\"(res://[^\"]+)\"")
var _re_wrapper := RegEx.create_from_string("(?m)^static\\s+var\\s+([A-Za-z_]\\w*)[^=\\n]*=\\s*[A-Za-z_]\\w*\\.new\\(")


func extension_name() -> String:
	return "asset_registry"


func setup(analyzer) -> void:
	_markers = analyzer.get_config("registry_markers", ["Generated by AssetRegistry"]).duplicate()
	var legacy = analyzer.get_config("registry_marker")
	if legacy != null:  # legacy single-string key
		_markers.append(String(legacy))
	_scripts = analyzer.get_config("registry_scripts", [])
	_patterns = analyzer.get_config("registry_patterns", {})


## Returning true suppresses the analyzer's wholesale quoted-path marking
## for this script; the registry's assets are gated by member usage instead.
func process_script(analyzer, path: String, raw: String, code: String) -> bool:
	var is_registry := path in _scripts
	if not is_registry:
		for marker in _markers:
			if not String(marker).is_empty() and String(marker) in raw:
				is_registry = true
				break
	if not is_registry:
		return false
	_parse(analyzer, path, code)
	return true


func _parse(analyzer, path: String, code: String) -> void:
	var cm := _re_class.search(code)
	if cm == null:
		analyzer.warn("asset_registry: %s has no class_name; skipped." % path)
		return
	var cname := cm.get_string(1)

	var members := {}
	for dm in _re_dictpath.search_all(code):
		if not members.has(dm.get_string(1)):
			members[dm.get_string(1)] = []
		members[dm.get_string(1)].append(dm.get_string(2))
	for sm in _re_strpath.search_all(code):
		if not members.has(sm.get_string(1)):
			members[sm.get_string(1)] = []
		members[sm.get_string(1)].append(sm.get_string(2))
	for pm in _re_preload.search_all(code):
		if not members.has(pm.get_string(1)):
			members[pm.get_string(1)] = []
		members[pm.get_string(1)].append(pm.get_string(2))

	var pval = _patterns.get(cname, "")
	var patterns: Array = []
	if pval is Array:
		patterns = pval
	elif pval is String and not String(pval).is_empty():
		patterns = [pval]
	var patternless := 0
	for wm in _re_wrapper.search_all(code):
		var member := wm.get_string(1)
		if not members.has(member):
			members[member] = []
		for p in patterns:
			members[member].append(String(p).replace("{member}", member))
		if patterns.is_empty() and members[member].is_empty():
			patternless += 1
	if patternless > 0:
		analyzer.warn("asset_registry: %s (%s): %d wrapper members have no asset mapping — add a registry_patterns[\"%s\"] entry like \"res://.../{member}.tscn\" if they load assets." % [cname, path, patternless, cname])

	_registries[cname] = {"script": path, "members": members, "used": {}}


func finalize(analyzer) -> bool:
	var text_cache: Dictionary = analyzer.get_text_cache()
	var changed := false
	for cname in _registries:
		var reg: Dictionary = _registries[cname]
		if not analyzer.is_used(reg["script"]):
			continue
		var access_re := RegEx.create_from_string("\\b%s\\s*\\.\\s*([A-Za-z_]\\w*)" % cname)
		var accessed := {}
		for file in text_cache:
			if file == reg["script"]:
				continue
			for am in access_re.search_all(text_cache[file]):
				accessed[am.get_string(1)] = file
		for member in reg["members"]:
			if reg["used"].has(member):
				continue
			var hit := ""
			if accessed.has(member):
				hit = "%s.%s in %s" % [cname, member, accessed[member]]
			else:
				var quoted_re := RegEx.create_from_string("[\"']%s[\"']" % member)
				for file in text_cache:
					if file != reg["script"] and quoted_re.search(text_cache[file]):
						hit = "\"%s\" (string) in %s" % [member, file]
						break
			if hit.is_empty():
				continue
			reg["used"][member] = hit
			changed = true
			for asset in reg["members"][member]:
				analyzer.mark_used(asset, "<registry %s.%s>" % [cname, member])
	return changed


func report(analyzer) -> Dictionary:
	var registries := {}
	var total_unused := 0
	for cname in _registries:
		var reg: Dictionary = _registries[cname]
		var unused_members := []
		var kept_members := []  # member unused, but assets referenced elsewhere
		for member in reg["members"]:
			if reg["used"].has(member):
				continue
			var kept := false
			for asset in reg["members"][member]:
				if analyzer.is_used(String(asset).simplify_path()):
					kept = true
					break
			(kept_members if kept else unused_members).append(member)
		unused_members.sort()
		kept_members.sort()
		total_unused += unused_members.size()
		registries[cname] = {
			"script": reg["script"],
			"total_members": reg["members"].size(),
			"used_members": reg["used"],
			"unused_members": unused_members,
			"unused_members_with_asset_kept": kept_members,
			"member_assets": reg["members"],
		}
	return {
		"summary": "%d registries, %d unused member(s)" % [registries.size(), total_unused],
		"registries": registries,
	}


func report_markdown(analyzer) -> PackedStringArray:
	var md := PackedStringArray()
	if _registries.is_empty():
		return md
	var data := report(analyzer)["registries"] as Dictionary
	var names := data.keys()
	names.sort()
	for cname in names:
		var rj: Dictionary = data[cname]
		md.append("### %s — %d/%d members used (%s)" % [cname, rj["used_members"].size(), rj["total_members"], String(rj["script"])])
		if not rj["unused_members"].is_empty():
			md.append("")
			md.append("Unused members — their assets are excluded:")
			for member in rj["unused_members"]:
				var assets: Array = rj["member_assets"][member]
				md.append("- %s%s" % [member, "" if assets.is_empty() else "  → " + ", ".join(assets)])
		if not rj["unused_members_with_asset_kept"].is_empty():
			md.append("")
			md.append("Unused members whose assets are still exported (referenced elsewhere) — registry entries deletable:")
			for member in rj["unused_members_with_asset_kept"]:
				md.append("- %s" % member)
		md.append("")
	return md
